"""Shared weighted, polarity-aware feature model (Python reference).

The semantics are documented once in docs/feature-model.md and implemented
identically here and in web/src/lib/features.ts. The golden fixtures in
shared/fixtures/feature-golden.json (regenerated by
tools/generate_feature_golden.py) verify that both implementations agree.

Feature keys:
  concept:<conceptId>    direct work concept          source "direct-concept"
  entity:<entityId>      one-hop contributor feature  source "contributor"/"organization"
  advisory:<categoryId>  content-guide profile        source "content-guide"

Values: clamp(weight/100, 0, 1) x (-1 if polarity < 0 else +1) x multiplier,
then multiplied by idf(key) = ln(1 + N/df(key)) at index build time.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any, Iterable, Sequence

# Features carried by more works than this are scored but never used for
# candidate generation (bounded fan-out, no all-pairs loops).
CANDIDATE_FEATURE_DF_CAP = 150

ROLE_MULTIPLIER_KEYS: dict[str, str] = {
    "creator": "creatorMultiplier",
    "composer": "creatorMultiplier",
    "lyricist": "creatorMultiplier",
    "music_artist": "creatorMultiplier",
    "director": "directorMultiplier",
    "author": "authorMultiplier",
    "screenwriter": "authorMultiplier",
    "producer": "producerMultiplier",
    "cast_member": "performerMultiplier",
    "voice_actor": "performerMultiplier",
    "performer": "performerMultiplier",
    "production_company": "organizationMultiplier",
    "record_label": "organizationMultiplier",
    "distributor": "organizationMultiplier",
    "publisher": "organizationMultiplier",
    "broadcaster": "organizationMultiplier",
}


@dataclass(frozen=True)
class Feature:
    key: str
    label: str
    value: float
    source: str
    category: str | None = None
    relation_type: str | None = None


@dataclass
class FeatureIndex:
    features_by_id: dict[int, dict[str, Feature]]
    vectors: dict[int, dict[str, float]]
    norms: dict[int, float]
    idf: dict[str, float]
    document_frequency: dict[str, int]
    postings: dict[str, list[int]]
    size: int


def _magnitude(weight: float) -> float:
    return max(0.0, min(1.0, weight / 100.0))


def _sign(polarity: float) -> float:
    return -1.0 if polarity < 0 else 1.0


def extract_features(
    concepts: Iterable[Sequence[Any]],
    contributors: Iterable[Sequence[Any]],
    advisories: Iterable[Sequence[Any]],
    feature_settings: dict[str, float],
) -> dict[str, Feature]:
    """Base (pre-IDF) features for one work.

    concepts:     (concept_id, label, category_label, weight, polarity)
    contributors: (entity_id, label, family, role, weight, polarity),
                  sorted by role ascending for deterministic role ties
    advisories:   (category_id, label, intensity)
    """

    by_key: dict[str, Feature] = {}
    direct = float(feature_settings["directConceptMultiplier"])
    for concept_id, label, category_label, weight, polarity in concepts:
        value = _magnitude(weight) * _sign(polarity) * direct
        if value == 0:
            continue
        key = f"concept:{concept_id}"
        by_key[key] = Feature(key, label, value, "direct-concept", category=category_label)

    for entity_id, label, family, role, weight, polarity in contributors:
        multiplier_key = ROLE_MULTIPLIER_KEYS.get(role)
        if multiplier_key is None:
            continue
        value = _magnitude(weight) * _sign(polarity) * float(feature_settings[multiplier_key])
        if value == 0:
            continue
        key = f"entity:{entity_id}"
        existing = by_key.get(key)
        if existing is not None and abs(existing.value) >= abs(value):
            continue
        source = "organization" if family in ("organization", "group") else "contributor"
        by_key[key] = Feature(key, label, value, source, relation_type=role)

    guide = float(feature_settings["contentGuideMultiplier"])
    for category_id, label, intensity in advisories:
        if intensity is None:
            continue
        value = _magnitude(intensity) * guide
        if value == 0:
            continue
        key = f"advisory:{category_id}"
        by_key[key] = Feature(key, label, value, "content-guide")

    return dict(sorted(by_key.items()))


def build_feature_index(base_features: dict[int, dict[str, Feature]]) -> FeatureIndex:
    document_frequency: dict[str, int] = {}
    for feature_map in base_features.values():
        for key in feature_map:
            document_frequency[key] = document_frequency.get(key, 0) + 1

    total = max(1, len(base_features))
    idf = {key: math.log(1 + total / df) for key, df in document_frequency.items()}

    features_by_id: dict[int, dict[str, Feature]] = {}
    vectors: dict[int, dict[str, float]] = {}
    norms: dict[int, float] = {}
    postings: dict[str, list[int]] = {}
    for work_id, feature_map in base_features.items():
        finals: dict[str, Feature] = {}
        vector: dict[str, float] = {}
        squared = 0.0
        for key, feature in feature_map.items():
            value = feature.value * idf.get(key, 0.0)
            if value == 0:
                continue
            finals[key] = Feature(
                key,
                feature.label,
                value,
                feature.source,
                category=feature.category,
                relation_type=feature.relation_type,
            )
            vector[key] = value
            squared += value * value
            postings.setdefault(key, []).append(work_id)
        features_by_id[work_id] = finals
        vectors[work_id] = vector
        norms[work_id] = math.sqrt(squared)

    return FeatureIndex(
        features_by_id=features_by_id,
        vectors=vectors,
        norms=norms,
        idf=idf,
        document_frequency=document_frequency,
        postings=postings,
        size=len(base_features),
    )


def factor_dict(feature: Feature, contribution: float) -> dict[str, Any]:
    factor: dict[str, Any] = {
        "id": feature.key,
        "label": feature.label,
        "contribution": contribution,
        "source": feature.source,
    }
    if feature.category is not None:
        factor["category"] = feature.category
    if feature.relation_type is not None:
        factor["relationType"] = feature.relation_type
    return factor


def similarity_between(
    index: FeatureIndex,
    a_id: int,
    b_id: int,
    top_count: int = 3,
) -> tuple[float, int, list[dict[str, Any]]]:
    a = index.vectors.get(a_id)
    b = index.vectors.get(b_id)
    norm_a = index.norms.get(a_id, 0.0)
    norm_b = index.norms.get(b_id, 0.0)
    if not a or not b or norm_a == 0 or norm_b == 0:
        return 0.0, 0, []

    small, large = (a, b) if len(a) <= len(b) else (b, a)
    dot = 0.0
    shared: list[tuple[float, str]] = []
    for key, value in small.items():
        other = large.get(key)
        if other is None:
            continue
        contribution = value * other
        dot += contribution
        shared.append((contribution, key))

    shared.sort(key=lambda entry: (-entry[0], entry[1]))
    meta = index.features_by_id.get(a_id, {})
    top_factors = []
    for contribution, key in shared[:top_count]:
        feature = meta.get(key)
        if feature is None:
            feature = Feature(key, key, 0.0, "direct-concept")
        top_factors.append(factor_dict(feature, contribution))
    return dot / (norm_a * norm_b), len(shared), top_factors


def similarity_candidates(
    index: FeatureIndex,
    entity_id: int,
    allowed: set[int] | None = None,
    df_cap: int = CANDIDATE_FEATURE_DF_CAP,
) -> set[int]:
    candidates: set[int] = set()
    vector = index.vectors.get(entity_id)
    if not vector:
        return candidates
    for key in vector:
        if index.document_frequency.get(key, 0) > df_cap:
            continue
        for other_id in index.postings.get(key, ()):  # noqa: B905 - list iteration
            if other_id == entity_id:
                continue
            if allowed is not None and other_id not in allowed:
                continue
            candidates.add(other_id)
    return candidates
